version: 2
jobs:
  build:
    docker:
      - image: python<3.7.1>

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/ISSlocationtask

    steps:
      - checkout

      - run:
          command: pip install working_directory.requirements.txt
      - run:
          command: working_directory.test_ISStask.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
