version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/ISSlocationtask

    steps:
      - checkout

      - run:
          command: pip install workking_directory.requirements.txt
      - run:
          command: working_directory.test_ISStask

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
